package org.yuemi.management.api.punishment;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * Represents the result of a punishment operation.
 *
 * @param success  whether the operation succeeded
 * @param message  descriptive result or error message
 * @param actionId optional action reference/ID (e.g. database ID from the third-party plugin)
 */
public record PunishmentResult(
        boolean success,
        @NotNull String message,
        @Nullable String actionId
) {

    /**
     * Creates a successful punishment result.
     *
     * @param message the success message
     * @return a new PunishmentResult instance
     */
    public static @NotNull PunishmentResult success(@NotNull String message) {
        return new PunishmentResult(true, message, null);
    }

    /**
     * Creates a successful punishment result with an action ID.
     *
     * @param message the success message
     * @param actionId the optional action ID generated by the provider
     * @return a new PunishmentResult instance
     */
    public static @NotNull PunishmentResult success(@NotNull String message, @Nullable String actionId) {
        return new PunishmentResult(true, message, actionId);
    }

    /**
     * Creates a failed punishment result.
     *
     * @param message the failure message
     * @return a new PunishmentResult instance
     */
    public static @NotNull PunishmentResult failure(@NotNull String message) {
        return new PunishmentResult(false, message, null);
    }
}
